# Generated by Django 2.2.3 on 2019-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeachDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('goa_event_date', models.CharField(default='11/11/2019', max_length=50)),
                ('date_for_goa_to_goa', models.CharField(max_length=50)),
                ('start_from', models.CharField(blank=True, default='Delhi', max_length=100)),
                ('duration', models.CharField(blank=True, default=0, max_length=50)),
                ('mode_of_transport', models.CharField(blank=True, default='Train', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('quad_with_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('triple_with_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('double_with_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('quad_wout_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('triple_wout_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('double_wout_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HoliDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('holi_event_date', models.CharField(default='11/11/2019', max_length=50)),
                ('date_for_goa_to_goa', models.CharField(default='11/11/2019', max_length=50)),
                ('start_from', models.CharField(blank=True, default='Delhi', max_length=100)),
                ('duration', models.CharField(blank=True, default=0, max_length=50)),
                ('mode_of_transport', models.CharField(blank=True, default='Train', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('quad_with_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('triple_with_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('double_with_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('quad_wout_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('triple_wout_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('double_wout_travel', models.DecimalField(decimal_places=2, default='0', max_digits=7)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
